setup: Data fake_frame_extractor.py fake_image_extraction.py ela.py ela_script.py srm_script.py

	python fake_image_extraction.py
	python vidtimit_download.py
	python ela_script.py fake_images fake_images_ela
	python ela_script.py real_images real_images_ela
	python srm_script.py fake_images fake_images_srm
	python srm_script.py real_images real_images_srm